In [12]:
import numpy as np
import pandas as pd

In [16]:
df = pd.read_csv("data\mushroom.data")
print(df.shape)
df.head(5)

(8123, 23)


p  x  s  n  t p.1  f  c n.1  k  ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0  e  x  s  y  t   a  f  c   b  k  ...   s  w   w   p   w  o   p   n   n  g
1  e  b  s  w  t   l  f  c   b  n  ...   s  w   w   p   w  o   p   n   n  m
2  p  x  y  w  t   p  f  c   n  n  ...   s  w   w   p   w  o   p   k   s  u
3  e  x  s  g  f   n  f  w   b  k  ...   s  w   w   p   w  o   e   n   a  g
4  e  x  y  y  t   a  f  c   b  n  ...   s  w   w   p   w  o   p   k   n  g

[5 rows x 23 columns]

In [18]:
data = df.values
X = data[:,1:-1]
y = data[:,0].ravel()
print(X[:3])
print(y[:3])

[['x' 's' 'y' 't' 'a' 'f' 'c' 'b' 'k' 'e' 'c' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'n' 'n']
 ['b' 's' 'w' 't' 'l' 'f' 'c' 'b' 'n' 'e' 'c' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'n' 'n']
 ['x' 'y' 'w' 't' 'p' 'f' 'c' 'n' 'n' 'e' 'e' 's' 's' 'w' 'w' 'p' 'w' 'o'
  'p' 'k' 's']]
['e' 'e' 'p']


In [26]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
(r, c) = X.shape
for i in range(0, c):
    X[:,i] =  LE.fit_transform(X[:,i])
y = LE.fit_transform(y)
print(X)
print(y)

[[5 2 9 ... 4 3 2]
 [0 2 8 ... 4 3 2]
 [5 3 8 ... 4 2 3]
 ...
 [2 2 4 ... 4 0 1]
 [3 3 4 ... 0 7 4]
 [5 2 4 ... 4 4 1]]
[0 0 1 ... 0 1 0]


In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(6498, 21) (6498,)
(1625, 21) (1625,)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

k = 5
knn = KNeighborsClassifier(n_neighbors=k, metric='euclidean')
knn.fit(X_train,y_train)
y_predict = knn.predict(X_test)
print('y_pred:\n', y_predict)
print('y_true:\n', y_test)

#Tinh do chinh xac
acc_score = metrics.accuracy_score(y_predict,y_test)
print('acurracy:\n', acc_score)

y_pred:
 [0 1 1 ... 0 0 0]
y_true:
 [0 1 1 ... 0 0 0]
acurracy:
 0.9981538461538462


In [30]:
from sklearn import svm

svm_classifier = svm.SVC(kernel='linear', gamma=0.01, C=100.)
svm_classifier.fit(X_train, y_train)

y_pred_svm = svm_classifier.predict(X_test)
print('predict:\n', y_pred_svm)
print('y_true:\n', y_test)

acc_score_svm = metrics.accuracy_score(y_pred_svm,y_test)
print('acurracy:\n', acc_score_svm)

predict:
 [0 1 1 ... 0 1 0]
y_true:
 [0 1 1 ... 0 0 0]
acurracy:
 0.9587692307692308


In [32]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model = model.fit(X_train, y_train)
y_pred_Logistic = model.predict(X_test)
print(y_pred_Logistic)

acc_score_logistic = metrics.accuracy_score(y_pred_Logistic, y_test)
print('acurracy:\n', acc_score_logistic)

[0 1 1 ... 0 1 0]
acurracy:
 0.9575384615384616


c:\users\andao\appdata\local\programs\python\python38-32\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
